import { useMemo, useRef, useState } from "react";
import { Clipboard, Copy, Download, FileText, Folder, FolderPlus, MoreHorizontal, Move, FileSpreadsheet, Trash2, Eye, Upload, Search } from "lucide-react";
import type { Project, ProjectFolder, ProjectPatch } from "../lib/projectStore";
import type { UploadedDocument } from "../lib/documentStore";
import { deleteDocument, documentKindFor, fileToDataUrl, MAX_DOCUMENT_BYTES, saveDocument, DOCUMENT_ACCEPT, type DocumentKind } from "../lib/documentStore";
import { useLanguage } from "../lib/i18n";
import Dialog from "./Dialog";
import DocumentViewer from "./DocumentViewer";
import { emitGuideAction } from "../lib/featureGuides";

export default function FolderManager({ owner, projects, folders, documents, onOpen, onManage, onDuplicate, onRenameFolder, onDeleteFolder, onCreateFolder, onDocumentsChanged }: { owner: string | null; projects: Project[]; folders: ProjectFolder[]; documents: UploadedDocument[]; onOpen:(p:Project)=>void; onManage:(p:Project,patch:ProjectPatch)=>Promise<void>; onDuplicate:(p:Project,title:string,target?:string|null)=>Promise<void>; onRenameFolder:(f:ProjectFolder,name:string)=>Promise<void>; onDeleteFolder:(f:ProjectFolder)=>Promise<void>; onCreateFolder:()=>void; onDocumentsChanged:()=>void }) {
  const { t, language } = useLanguage();
  const [active,setActive]=useState<string|null>(null), [selected,setSelected]=useState<Project|null>(null), [selectedDocument,setSelectedDocument]=useState<UploadedDocument|null>(null), [clipboard,setClipboard]=useState<Project|null>(null), [dialog,setDialog]=useState<"rename"|"move"|"delete"|null>(null), [value,setValue]=useState(""), [busy,setBusy]=useState(false), [documentsView,setDocumentsView]=useState(false);
  const [folderAction, setFolderAction] = useState<{ folder: ProjectFolder; kind: "rename" | "delete" } | null>(null);
  const [folderValue, setFolderValue] = useState("");
  const [documentQuery, setDocumentQuery] = useState("");
  const [documentFilter, setDocumentFilter] = useState<DocumentKind | "all">("all");
  const [uploading, setUploading] = useState(false);
  const [documentError, setDocumentError] = useState("");
  const documentInput = useRef<HTMLInputElement>(null);
  const canManageSelected = !!selected && (!selected.shared || selected.accessRole !== "viewer");
  const list=projects.filter(p=>!p.deletedAt && (active===null || p.folderId===active));
  const documentList = useMemo(() => documents.filter(file => (active === null || file.folderId === active) && (documentFilter === "all" || file.kind === documentFilter) && (!documentQuery.trim() || file.name.toLocaleLowerCase().includes(documentQuery.trim().toLocaleLowerCase()))), [documents, active, documentFilter, documentQuery]);
  const folderName=active?folders.find(f=>f.id===active)?.name:t("workspace");
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();setDialog(null);setSelected(null);}finally{setBusy(false);}};
  const removeDocument = async (document: UploadedDocument) => { if (!window.confirm(language === "vi" ? `Xóa ${document.name} khỏi thư viện tài liệu?` : `Delete ${document.name} from the document library?`)) return; await deleteDocument(document.owner === "guest" ? null : document.owner, document.id); setSelectedDocument(null); onDocumentsChanged(); };
  const uploadDocuments = async (files: File[]) => {
    if (!files.length || uploading) return;
    setUploading(true); setDocumentError("");
    const errors: string[] = [];
    for (const file of files) {
      const kind = documentKindFor(file.name, file.type);
      if (!kind) { errors.push(`${file.name}: ${language === "vi" ? "định dạng không hỗ trợ" : "unsupported format"}`); continue; }
      if (file.size > MAX_DOCUMENT_BYTES) { errors.push(`${file.name}: ${language === "vi" ? "vượt quá 40 MB" : "over 40 MB"}`); continue; }
      try {
        const dataUrl = await fileToDataUrl(file);
        await saveDocument(owner, { name: file.name, mimeType: file.type || "application/octet-stream", kind, size: file.size, dataUrl, folderId: active });
        emitGuideAction("documents:uploaded", { name: file.name, kind });
      } catch (error) { errors.push(`${file.name}: ${error instanceof Error ? error.message : "upload failed"}`); }
    }
    if (errors.length) setDocumentError(errors.join(" · "));
    if (files.length !== errors.length) onDocumentsChanged();
    setUploading(false);
  };
  const downloadDocument = (file: UploadedDocument) => { const link = document.createElement("a"); link.href = file.dataUrl; link.download = file.name; link.click(); emitGuideAction("documents:download", { documentId: file.id, kind: file.kind }); };
  return <section className="folder-manager">
    <div className="folder-manager-side">
      <div className="manager-title"><strong>{t("folders")}</strong><button className="icon-button folder-manager-new-folder" aria-label={t("newFolder")} onClick={onCreateFolder}><FolderPlus size={17}/></button></div>
      <button className={!documentsView && active===null?"manager-folder active":"manager-folder"} onClick={()=>{setDocumentsView(false);setActive(null);setSelectedDocument(null);}}><Folder size={17}/>{t("workspace")}</button>
      {folders.map(f=><div className={`manager-folder-row ${!documentsView && active===f.id ? "active" : ""}`} key={f.id}>
        <button className={!documentsView && active===f.id?"manager-folder active":"manager-folder"} onClick={()=>{setDocumentsView(false);setActive(f.id);setSelectedDocument(null);}}><Folder size={17}/><span>{f.name}</span><small>{projects.filter(p=>p.folderId===f.id&&!p.deletedAt).length}</small></button>
        <button type="button" className="manager-folder-actions icon-button" aria-label={`${t("folderActions")}: ${f.name}`} title={t("folderActions")} onClick={event=>{event.stopPropagation();setFolderValue(f.name);setFolderAction({folder:f,kind:"rename"});}}><MoreHorizontal size={17}/></button>
      </div>)}
      <button className={documentsView?"manager-folder manager-documents active":"manager-folder manager-documents"} onClick={()=>{setDocumentsView(true);setSelectedDocument(null);emitGuideAction("documents:library");}}><FileSpreadsheet size={17}/><span>{language === "vi" ? "Tài liệu đã tải lên" : "Uploaded documents"}</span><small>{documents.length}</small></button>
    </div>
    <div className="folder-manager-main">
      {documentsView ? <>
        <div className="manager-toolbar"><div><span className="eyebrow">{language === "vi" ? "THƯ VIỆN TÀI LIỆU" : "DOCUMENT LIBRARY"}</span><h1>{language === "vi" ? "Tài liệu đã tải lên" : "Uploaded documents"}</h1><p className="manager-local-storage-note">{language === "vi" ? "Lưu trên thiết bị này · PDF, DOCX, PPTX, XLSX" : "Stored on this device · PDF, DOCX, PPTX, XLSX"}</p></div><div className="manager-toolbar-actions"><span className="manager-count">{documentList.length}</span><input ref={documentInput} hidden type="file" multiple accept={DOCUMENT_ACCEPT} onChange={event => { void uploadDocuments([...event.target.files ?? []]); event.currentTarget.value = ""; }}/><button type="button" className="primary-button" disabled={uploading} onClick={() => documentInput.current?.click()}><Upload size={16}/>{uploading ? (language === "vi" ? "Đang tải…" : "Uploading…") : (language === "vi" ? "Tải tài liệu lên" : "Upload documents")}</button></div></div>
        <div className="document-library-controls"><label className="document-search"><Search size={16}/><input value={documentQuery} onChange={event => setDocumentQuery(event.target.value)} placeholder={language === "vi" ? "Tìm tài liệu…" : "Search documents…"}/></label><select value={documentFilter} onChange={event => setDocumentFilter(event.target.value as DocumentKind | "all")} aria-label={language === "vi" ? "Lọc loại tài liệu" : "Filter document type"}><option value="all">{language === "vi" ? "Tất cả loại" : "All types"}</option><option value="pdf">PDF</option><option value="docx">DOCX</option><option value="pptx">PPTX</option><option value="xlsx">XLSX</option></select></div>
        {documentError && <p className="form-error" role="alert">{documentError}</p>}
        {selectedDocument ? <div className="manager-document-viewer"><button className="secondary-button manager-back-button" onClick={()=>{setSelectedDocument(null);emitGuideAction("documents:back");}}>← {language === "vi" ? "Danh sách tài liệu" : "Back to documents"}</button><DocumentViewer source={selectedDocument} onReady={detail => emitGuideAction("documents:viewer-ready", { ...detail, documentId: selectedDocument.id, kind: selectedDocument.kind })}/><div className="document-viewer-footer-actions"><button type="button" className="secondary-button" onClick={() => downloadDocument(selectedDocument)}><Download size={15}/>{language === "vi" ? "Tải xuống" : "Download"}</button><button className="text-danger-button" onClick={()=>void removeDocument(selectedDocument)}><Trash2 size={15}/>{language === "vi" ? "Xóa tài liệu" : "Delete document"}</button></div></div> : !documentList.length ? <div className="empty-state"><FileSpreadsheet size={42}/><h2>{documents.length ? (language === "vi" ? "Không có tài liệu phù hợp" : "No matching documents") : (language === "vi" ? "Chưa có tài liệu đã tải lên" : "No uploaded documents")}</h2><p>{language === "vi" ? "Bấm Tải tài liệu lên để lưu PDF, DOCX, PPTX hoặc XLSX trên thiết bị này." : "Click Upload documents to store PDF, DOCX, PPTX or XLSX on this device."}</p></div> : <div className="file-table document-file-table">{documentList.map(document=><div className="file-row" data-document-id={document.id} data-document-kind={document.kind} key={document.id} onClick={()=>{setSelectedDocument(document);emitGuideAction(document.kind === "pdf" ? "documents:open:pdf" : "documents:open", { documentId: document.id, kind: document.kind });}} onDoubleClick={()=>{setSelectedDocument(document);emitGuideAction(document.kind === "pdf" ? "documents:open:pdf" : "documents:open", { documentId: document.id, kind: document.kind });}}><FileSpreadsheet size={19}/><span title={document.name}>{document.name}</span><small>{document.kind.toUpperCase()} · {new Date(document.updatedAt).toLocaleDateString()}</small><div className="document-row-actions"><button className="icon-button" aria-label={`${language === "vi" ? "Tải xuống" : "Download"}: ${document.name}`} onClick={event=>{event.stopPropagation();downloadDocument(document);}}><Download size={16}/></button><button className="icon-button" aria-label={`${language === "vi" ? "Xem" : "View"}: ${document.name}`} onClick={event=>{event.stopPropagation();setSelectedDocument(document);emitGuideAction(document.kind === "pdf" ? "documents:open:pdf" : "documents:open", { documentId: document.id, kind: document.kind });}}><Eye size={17}/></button></div></div>)}</div>}
      </> : <>
        <div className="manager-toolbar"><div><span className="eyebrow">{t("folders")}</span><h1>{folderName}</h1></div><div className="actions"><button className="secondary-button" disabled={!selected} onClick={()=>selected&&setClipboard(selected)}><Copy size={16}/>{t("copy")}</button><button className="secondary-button" disabled={!clipboard} onClick={()=>clipboard&&void run(()=>onDuplicate(clipboard,`${clipboard.title} — ${t("copySuffix")}`,active))}><Clipboard size={16}/>{t("paste")}</button><button className="secondary-button" disabled={!canManageSelected} onClick={()=>{if(selected&&canManageSelected){setValue(selected.folderId??"");setDialog("move")}}}><Move size={16}/>{t("move")}</button><button className="primary-button" disabled={!selected} onClick={()=>selected&&void run(()=>onDuplicate(selected,`${selected.title} — ${t("copySuffix")}`,active))}>{t("duplicate")}</button></div></div>
        {!list.length?<div className="empty-state"><Folder size={42}/><h2>{t("emptyFolder")}</h2></div>:<div className="file-table">{list.map(p=><div className={selected?.id===p.id?"file-row selected":"file-row"} key={p.id} onClick={()=>setSelected(p)} onDoubleClick={()=>onOpen(p)}><FileText size={19}/><span>{p.title}</span><small>{new Date(p.updatedAt).toLocaleDateString()}</small><button className="icon-button" disabled={p.shared&&p.accessRole==="viewer"} aria-label={`${t("fileActions")}: ${p.title}`} onClick={e=>{e.stopPropagation();if(p.shared&&p.accessRole==="viewer")return;setSelected(p);setValue(p.title);setDialog("rename")}}><MoreHorizontal size={18}/></button></div>)}</div>}
      </>}
    </div>
    {dialog&&selected&&<Dialog title={t(dialog)} onClose={()=>setDialog(null)}>{dialog==="rename"&&<form onSubmit={e=>{e.preventDefault();void run(()=>onManage(selected,{title:value.trim()}))}}><input autoFocus required value={value} onChange={e=>setValue(e.target.value)}/><footer className="actions"><button type="button" onClick={()=>setDialog(null)}>{t("cancel")}</button><button className="primary-button" disabled={busy}>{t("save")}</button></footer></form>}{dialog==="move"&&<form onSubmit={e=>{e.preventDefault();void run(()=>onManage(selected,{folderId:value||null}))}}><select value={value} onChange={e=>setValue(e.target.value)}><option value="">{t("noFolder")}</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><footer className="actions"><button type="button" onClick={()=>setDialog(null)}>{t("cancel")}</button><button className="primary-button">{t("save")}</button></footer></form>}{dialog==="delete"&&<><p>{t("deleteFileHint")}</p><button className="danger-button" onClick={()=>void run(()=>onManage(selected,{deletedAt:new Date().toISOString()}))}>{t("delete")}</button></>}</Dialog>}
    {folderAction?.kind === "rename" && <Dialog title={t("renameFolder")} onClose={() => setFolderAction(null)}><form onSubmit={event => { event.preventDefault(); const nextName = folderValue.trim(); if (!nextName || busy) return; setBusy(true); void onRenameFolder(folderAction.folder, nextName).then(() => { emitGuideAction("folder:renamed", { folderId: folderAction.folder.id, name: nextName }); setFolderAction(null); }).catch(() => undefined).finally(() => setBusy(false)); }}><label>{t("name")}<input autoFocus required maxLength={80} value={folderValue} onChange={event => setFolderValue(event.target.value)}/></label><footer className="actions"><button type="button" className="secondary-button" disabled={busy} onClick={() => setFolderAction(null)}>{t("cancel")}</button><button className="primary-button" disabled={busy || !folderValue.trim()}>{busy ? t("saving") : t("save")}</button></footer></form><button type="button" className="text-danger-button" disabled={busy} onClick={() => setFolderAction({ ...folderAction, kind: "delete" })}>{t("deleteFolder")}</button></Dialog>}
    {folderAction?.kind === "delete" && <Dialog title={t("deleteFolder")} onClose={() => setFolderAction(null)}><p>{t("deleteFolderHint")}</p><footer className="actions"><button type="button" className="secondary-button" disabled={busy} onClick={() => setFolderAction(null)}>{t("cancel")}</button><button type="button" className="danger-button" disabled={busy} onClick={() => { setBusy(true); void onDeleteFolder(folderAction.folder).then(() => { emitGuideAction("folder:deleted", { folderId: folderAction.folder.id }); if (active === folderAction.folder.id) { setActive(null); setSelected(null); } setFolderAction(null); }).catch(() => undefined).finally(() => setBusy(false)); }}>{busy ? t("saving") : t("deleteFolder")}</button></footer></Dialog>}
  </section>;
}
