import { describe, expect, it } from "vitest";
import { applyGraph, blankBoard, connect, duplicateElement, elementBounds, hiddenNodes, moveElement, parseBoard, removeElement, resizeElement } from "./board";
import { en, vi } from "./i18n";
const board = () => ({ ...blankBoard(), nodes: [{ id: "a", label: "A", x: 0, y: 0, width: 150, height: 60 }, { id: "b", label: "B", x: 250, y: 0, width: 150, height: 60 }] });
describe("Editable canvas model", () => {
  it("starts with no sample content", () => { const b = blankBoard(); expect(b.nodes.length + b.texts.length + b.shapes.length + b.drawings.length + b.edges.length).toBe(0); expect(b.id).not.toBe(blankBoard().id); });
  it("moves independent strokes without touching nodes", () => { const b = { ...board(), drawings: [{ id: "p", points: [{ x: 2, y: 3 }], color: "#123456", width: 3, opacity: 1 }] }; const next = moveElement(b, { kind: "drawings", id: "p" }, 20, 30); expect(next.drawings[0].points[0]).toEqual({ x: 22, y: 33 }); expect(next.nodes).toBe(b.nodes); });
  it("resizes drawings and keeps originals immutable", () => { const b = { ...board(), drawings: [{ id: "p", points: [{ x: 0, y: 0 }, { x: 10, y: 10 }], color: "#123456", width: 3, opacity: 1 }] }; const next = resizeElement(b, { kind: "drawings", id: "p" }, 30, 40); expect(next.drawings[0].points[1]).toEqual({ x: 30, y: 40 }); expect(b.drawings[0].points[1]).toEqual({ x: 10, y: 10 }); });
  it("connectors track ids after moves and are removed with endpoints", () => { const b = connect(board(), "a", "b"); const next = moveElement(b, { kind: "nodes", id: "a" }, 100, 20); expect(next.edges).toEqual(b.edges); expect(next.nodes[0].x).toBe(100); expect(removeElement(next, { kind: "nodes", id: "a" }).edges).toHaveLength(0); expect(connect(b, "a", "b").edges).toHaveLength(1); });
  it("duplicates with fresh IDs and offsets", () => { const b = board(), next = duplicateElement(b, { kind: "nodes", id: "a" }); expect(next.board.nodes).toHaveLength(3); expect(next.selection.id).not.toBe("a"); expect(next.board.nodes[2].x).toBe(24); });
  it("AI Apply preserves existing content and remaps all IDs on repeated applies", () => { const b = board(), g = { title: "Map", nodes: [{ id: "a", label: "AI A" }, { id: "b", label: "AI B" }], edges: [{ id: "edge", source: "a", target: "b" }] }; const once = applyGraph(b, g), twice = applyGraph(once, g); expect(twice.nodes).toHaveLength(6); expect(new Set(twice.nodes.map(n => n.id)).size).toBe(6); expect(twice.title).toBe(b.title); expect(twice.edges[0].source).not.toBe("a"); });
  it("bounds legacy text and supports multiline", () => { const b = { ...board(), texts: [{ id: "t", x: 20, y: 40, width: 200, text: "one\ntwo" }] }; expect(elementBounds(b, { kind: "texts", id: "t" })?.height).toBeGreaterThan(40); });
  it("validates old file format and rejects corrupt geometry", () => { expect(parseBoard(board()).nodes).toHaveLength(2); expect(() => parseBoard({ ...board(), viewport: { x: 0, y: 0, scale: 0 } })).toThrow(); expect(() => parseBoard({ ...board(), nodes: [{ ...board().nodes[0], width: NaN }] })).toThrow(); expect(() => parseBoard({ ...board(), nodes: [board().nodes[0], board().nodes[0]] })).toThrow(); });
  it("collapses descendants safely even with cycles", () => { const b = connect(connect(board(), "a", "b"), "b", "a"); b.nodes[0] = { ...b.nodes[0], collapsed: true } as typeof b.nodes[0]; expect([...hiddenNodes(b)]).toEqual(["b"]); });
  it("has full parity between Vietnamese and English UI dictionaries", () => { expect(Object.keys(vi).sort()).toEqual(Object.keys(en).sort()); expect(Object.values(vi).every(Boolean)).toBe(true); });
});
