import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from "react";
import { DEFAULT_THEME, isTheme, themeBrowserColor, type Theme } from "./theme";
export type { Theme } from "./theme";

export const en = {
  title: "Title", commandPalette: "Quick actions", commandSearch: "Search projects and actions…", commandHint: "Open with Ctrl/⌘ + K", noCommands: "No matching action or project", goToFlashcards: "Open flashcards", openSettings: "Open settings", importProject: "Import project",
  copyElements: "Copy elements", pasteElements: "Paste elements",
  selectedElements: "elements selected", bringFront: "Bring to front", sendBack: "Send to back", bringForward: "Bring forward", sendBackward: "Send backward",
  group: "Group", ungroup: "Ungroup", addChild: "Add child", addSibling: "Add sibling", reparentHint: "Alt-drag one node onto another to change its parent. Shift+Enter edits the label.",
  fitCanvas: "Fit canvas", fitSelection: "Go to selection", minimap: "Minimap", favorites: "Favorites", trash: "Trash", restore: "Restore", favorite: "Add to favorites", unfavorite: "Remove favorite", moveToTrash: "Move to trash", projectActions: "Project actions", copySuffix: "copy", trashEmpty: "Trash is empty", trashHint: "Files here can be restored. They are not permanently deleted.",
  arrangeMap: "Arrange mind map",
  flashcards: "Flashcards", flashcardsHint: "Turn your notes into small, reviewable prompts.", decks: "Decks", newDeck: "New deck", renameDeck: "Rename deck", deleteDeck: "Delete deck", deleteDeckHint: "Delete “{{name}}” and all of its cards? This cannot be undone.", deckName: "Deck name", noDecks: "No decks yet", chooseDeck: "Choose a deck", chooseDeckHint: "Create a deck, then add your first card.", linkProject: "Link to project", noLinkedProject: "No linked project", linkedProject: "Linked project", cardCount: "{{count}} cards", dueCount: "{{count}} due", newCard: "New card", editCard: "Edit card", deleteCard: "Delete card", allCards: "All cards", review: "Review", startReview: "Start review", noCards: "No cards in this deck", noCardsHint: "Add a question and answer to begin reviewing.", questionSide: "Question", answerSide: "Answer", questionPlaceholder: "What do you want to remember?", answerPlaceholder: "Write the answer or explanation…", sourcePage: "Source page", optional: "Optional", flashcardNameRequired: "Enter a deck name.", flashcardSidesRequired: "Enter both the question and answer.", flashcardPageInvalid: "Source page must be a positive whole number.", flashcardCloudHint: "Flashcards are stored in Supabase for this account.", flashcardLocalHint: "Flashcards are stored on this browser until the database migration is applied.", dueNow: "Due now", nextReview: "Next review {{date}}", showAnswer: "Show answer", ratePrompt: "How well did you remember it?", again: "Again", hard: "Hard", good: "Good", easy: "Easy", reviewProgress: "{{current}} of {{total}}", reviewKeyboardHint: "Your rating is saved immediately.", reviewComplete: "Review complete", reviewCompleteHint: "You reviewed {{count}} cards.", nothingDue: "Nothing is due", nothingDueHint: "There are no cards waiting for review right now.", backToCards: "Back to cards", newCards: "New", difficultCards: "Difficult", learnedCards: "Learned", reviewDue: "Review due", reviewNew: "Study new", reviewDifficult: "Practice difficult", dailyGoal: "Daily goal", sessionProgress: "Session progress", cardSearch: "Search cards…",
  generateFlashcards: "Generate with AI", aiFlashcardHint: "Use pasted text, a project canvas, a clipboard screenshot, or a supported document/image. AI returns an editable preview; nothing is added until you apply it.", aiSource: "Source", aiSourceText: "Paste text", aiSourceProject: "Project canvas", aiSourcePdf: "PDF document", sourceText: "Source text", sourceTextPlaceholder: "Paste the notes or extracted text you want to study…", sourceProject: "Project", chooseProject: "Choose a project", sourceProjectHint: "Visible text and mind-map labels from the project will be sent to the server.", maxGeneratedCards: "Maximum cards", aiMaxCardsInvalid: "Choose between 3 and 50 cards.", generatingFlashcards: "Reading the source and generating flashcards…", aiPreviewHint: "Review every question and answer. Edit or remove anything before applying to this deck.", flashcardSetTitle: "Preview title", removePreviewCard: "Remove preview card", addPreviewCard: "Add preview card", backToSource: "Back to source", applyToDeck: "Add to deck", generatePreview: "Generate preview", aiTextRequired: "Paste some source text first.", aiProjectRequired: "Choose a project first.", aiProjectEmpty: "This project has no readable text or mind-map labels.", aiPdfRequired: "Choose a PDF first.", aiFlashcardError: "Could not generate flashcards.",
  workspace: "Workspace", recent: "Recent files", folders: "Folders", manageFolders: "Manage folders", newFolder: "New folder", folderActions: "Folder actions", renameFolder: "Rename folder", deleteFolder: "Delete folder", deleteFolderHint: "Projects in this folder will be moved back to Workspace. The folder itself will be deleted.", copy: "Copy", paste: "Paste", fileActions: "File actions", emptyFolder: "This folder is empty", deleteFileHint: "Move this project to Trash?", theme: "Appearance", themeChoose: "Choose a color theme", themeLightCollection: "Light themes", themeDarkCollection: "Dark themes", themeLight: "Aurora Light", themeLightHint: "Clean ivory surfaces with vivid violet accents.", themeOcean: "Ocean Breeze", themeOceanHint: "Airy ice blue with ocean and cyan accents.", themeMint: "Mint Frost", themeMintHint: "Fresh mint surfaces with crisp teal contrast.", themeSunset: "Sunset Coral", themeSunsetHint: "Warm cream, coral and tangerine energy.", themeBerry: "Berry Pop", themeBerryHint: "Soft rose surfaces with vibrant raspberry color.", themeDark: "Midnight Dark", themeDarkHint: "Deep plum surfaces with bright lilac contrast.", themeCobalt: "Cobalt Night", themeCobaltHint: "Deep navy with electric blue highlights.", themeCyber: "Cyber Teal", themeCyberHint: "Dark cyan surfaces with luminous aqua accents.", themeForest: "Emerald Forest", themeForestHint: "Deep green surfaces with fresh mint accents.", themeSlate: "Nordic Slate", themeSlateHint: "Cool graphite with calm periwinkle contrast.",
  mobileMenu: "Open navigation", collapseFolder: "Collapse folder", expandFolder: "Expand folder", resizeSidebar: "Resize navigation", resetSidebarWidth: "Double-click to reset width", cloudConflictTitle: "Choose which version to keep", cloudConflictHint: "This project changed in the cloud while this device still had local edits. Autosave is paused so neither version is silently overwritten.", deviceVersion: "This device", latestCloudVersion: "Latest cloud version", conflictSafety: "MindCanvas creates a recovery checkpoint before replacing either version.", useCloudVersion: "Use cloud version", saveAsCopy: "Save device version as a copy", saveDeviceToCloud: "Save this device to cloud",
  newProject: "New project", projects: "Projects", untitled: "Untitled canvas", name: "Name",
  create: "Create", cancel: "Cancel", close: "Close", save: "Save", open: "Open",
  rename: "Rename", move: "Move to folder", noFolder: "No folder", search: "Search projects…",
  newest: "Last edited", alphabetical: "Name A–Z", empty: "Your ideas start here",
  emptyHint: "Create a blank canvas or import a MindCanvas file.", noResults: "No matching projects",
  local: "On this device", cloud: "Cloud workspace", guest: "Guest", login: "Sign in with Google",
  logout: "Sign out", checking: "Checking session…", loading: "Loading…", settings: "Settings",
  language: "Language", saved: "Saved to cloud", localSaved: "Saved on this device",
  saving: "Saving…", pending: "Waiting to sync", offline: "Offline · local copy kept",
  syncCenter: "Sync center", syncCenterCloudHint: "See what is stored on this device and what is waiting to reach your private cloud workspace.", syncCenterLocalHint: "This guest workspace stays on this device. Sign in when you want to sync across devices.", networkOnline: "Online", networkOffline: "Offline", networkOnlineHint: "Cloud services are reachable.", networkOfflineHint: "Edits continue on this device.", syncUpToDate: "Cloud is up to date", syncCloud: "Cloud sync", syncDeviceOnly: "Device storage", pendingFiles: "{{count}} file(s) waiting", signInToSync: "Sign in to enable cloud sync.", syncQueue: "Waiting to sync", syncQueueEmpty: "No changes are waiting to sync.", syncLocalReady: "Your projects are available on this device.", offlineSafety: "Edits are saved to a local offline store before cloud upload is attempted.", syncNow: "Sync now",
  installApp: "Install app", installAppTitle: "Install MindCanvas", installAppHint: "Install the web app for a full-screen workspace, faster launch and offline access to projects already opened on this device.", installNow: "Install on this device", appInstalled: "App installed", appInstalledHint: "MindCanvas is already running as an installed app on this device.", iosInstallHint: "On iPhone or iPad, open this page in Safari, tap Share, then choose Add to Home Screen.", browserInstallHint: "Use Install app in your browser menu if the install button has not appeared yet.", pwaOfflineHint: "The editor shell and cached projects can open without a network. AI, Google sign-in and cloud sync resume when you reconnect.", updateReady: "A new MindCanvas version is ready.", updateNow: "Update now",
  saveError: "Save failed", retry: "Retry", error: "Something went wrong", import: "Import file",
  export: "Download file", exportSvg: "Export SVG", exportPng: "Export PNG", exportSvgHint: "Download a scalable vector image of the canvas.", exportPngHint: "Download a PNG image of the canvas.", importError: "Invalid MindCanvas file (maximum 40 MB).",
  exportHint: "Download a private copy. Send the file to share; it does not grant cloud access.",
  select: "Select", hand: "Pan", text: "Text", pen: "Pen", highlighter: "Highlighter",
  insertMedia: "Insert media", insertMediaHint: "Add an image, video, or audio file", recordAudio: "Record audio", stopRecording: "Stop recording", recording: "Recording {{seconds}}s", media: "Media", image: "Image", video: "Video", audio: "Audio", mediaFileTooLarge: "This media file is too large (maximum 12 MB).", recordingUnsupported: "Audio recording is not supported in this browser.", recordingPermissionDenied: "Microphone access was denied.",
  embedWeb: "Embed web page", embedUrl: "Web or video URL", embedTitle: "Title", embedPlaceholder: "https://… or a YouTube link", embedHint: "YouTube links become playable embeds. Some websites block being shown inside another page.", insertEmbed: "Insert embed", embed: "Embedded content", webPage: "Web page", youtube: "YouTube", embedBlocked: "This website may block embedded viewing.", pasteImage: "Paste screenshot image", pasteImageHint: "Read an image from the system clipboard",
  rect: "Rectangle", ellipse: "Ellipse", connector: "Connector", node: "Mind-map node",
  newNode: "New idea", rootNode: "Main idea", newText: "Type here", editText: "Edit text",
  undo: "Undo", redo: "Redo", duplicate: "Duplicate", delete: "Delete", versionHistory: "Version history", versionHint: "Create an explicit checkpoint when you want a stable recovery point. Panning and zooming do not create history entries.", saveCheckpoint: "Save checkpoint", noVersions: "No checkpoints yet", cloudVersion: "Cloud", localVersion: "This device", restoreCreatesUndo: "Restoring creates one undoable change, and the current state is checkpointed first.", zoomIn: "Zoom in",
  zoomOut: "Zoom out", resetZoom: "Reset view", properties: "Properties", layers: "Elements", searchElements: "Search elements…", noElements: "This canvas has no elements", noElementsFound: "No matching elements", grouped: "Grouped", layerDragHint: "Drag a row to reorder it. The first row is the front layer.", snap: "Smart guides", alignLeft: "Align left", alignCenter: "Align center", alignRight: "Align right", alignTop: "Align top", alignMiddle: "Align middle", alignBottom: "Align bottom", distributeHorizontal: "Distribute horizontally", distributeVertical: "Distribute vertically", rotate: "Rotate", lock: "Lock", unlock: "Unlock", hide: "Hide", show: "Show",
  color: "Color", label: "Label", width: "Width", height: "Height", rotation: "Rotation (degrees)", resetRotation: "Reset to 0°", crop: "Crop", resetCrop: "Reset crop", cropTop: "Top %", cropRight: "Right %", cropBottom: "Bottom %", cropLeft: "Left %", trimStart: "Start (seconds)", trimEnd: "End (seconds)", trimHint: "Playback is limited to this range; the original file is unchanged.", resetTrim: "Reset trim", clipboardImageUnavailable: "No image was found in the clipboard.", seconds: "seconds", fontSize: "Font size", opacity: "Opacity", alpha: "Opacity", resetAlpha: "Reset opacity", bold: "Bold", italic: "Italic", underline: "Underline", bulletedList: "Bulleted list", checklist: "Checklist", textBackground: "Text background", clearBackground: "Remove background",
  canvasBackground: "Canvas background", backgroundDots: "Dots", backgroundGrid: "Grid", backgroundRuled: "Ruled paper", backgroundGraph: "Graph paper", backgroundIsometric: "Isometric", backgroundPlain: "Blank",
  stroke: "Stroke width", collapse: "Collapse branch", expand: "Expand branch",
  canvasHint: "Drag empty space to select · Shift+click to add · Space+drag to pan",
  connectorHint: "Select a source node or shape, then a destination.",
  selectHint: "Select an element to change its position, size or color.",
  textHint: "Click anywhere to type. Escape cancels; Ctrl/⌘ + Enter finishes.",
  ai: "PDF → mind map", choosePdf: "Choose PDF", pdfHint: "Up to 10 MB. A text-based PDF is required.", pdfPreview: "PDF preview", pageRange: "Pages", allPages: "All pages", fromPage: "From", toPage: "To", applyTo: "Apply to", currentCanvas: "Current canvas", newCanvas: "New canvas", selectedPages: "Selected pages", previewChanges: "Review generated changes before applying.", rollbackHint: "Applying is one undoable canvas change.", noTextPages: "No readable text was found in the selected pages.",
  generate: "Generate preview", generating: "Reading PDF and generating…", apply: "Apply to canvas",
  aiHint: "Review and edit the labels below. Your existing canvas is preserved.",
  aiError: "Could not process the PDF. Check the API connection and model configuration.", aiQueueBusy: "AI is serving other requests right now. Wait about 15 seconds, then try again.", aiTemporarilyBusy: "Gemini is busy or the shared quota is temporarily limited. MindCanvas retried and switched fallback models; wait about 30 seconds, then try again.", aiModelUnavailable: "None of the configured Gemini models is available to this server key. Ask the owner to check GEMINI_MODELS on the API service.", aiSessionExpired: "Your sign-in session has expired. Sign out, sign in with Google again, then retry.",
  aiDemo: "The server returned demo data. Configure a real AI provider before applying.",
  aiSelectionTitle: "AI for selection", aiSelectionHint: "Transform only the selected text or mind-map nodes. Review the result before applying.", aiSelectionAction: "AI action", aiSummarize: "Summarize", aiExplain: "Explain", aiRewrite: "Rewrite", aiExpand: "Expand branches", aiSelectedContent: "Selected content", aiSelectionWorking: "Gemini is working on this selection…", aiSelectionError: "Could not process this selection.", aiResult: "Editable result", aiChildIdeas: "Child ideas", aiChildIdea: "Child idea", askAiSelection: "Use AI on selection", selectTextForAi: "Select text or mind-map nodes to use AI.",
  loginRequired: "Sign in to store PDFs and use AI.", nodes: "nodes", edges: "connections",
  page: "Page", openSource: "Open source PDF", openNewTab: "Open in new tab", sourceError: "Could not open the source PDF.", help: "Shortcuts", helpText: "V select · H pan · T text · P pen · R rectangle · O ellipse · C connector · Ctrl/⌘+K quick actions · Ctrl/⌘+Z undo · Ctrl/⌘+D duplicate · Ctrl/⌘+S save",
  accountHint: "Cloud projects belong to the signed-in account. Local projects stay on this browser.",
  fileTooLarge: "This file exceeds 10 MB.", noFolders: "No folders yet", copied: "Copy downloaded",
  updated: "Updated", saveBeforeLeave: "Keep this tab open until saving finishes, or export a backup.",
  drawHint: "Drag to draw. Switch to Select to move individual strokes.",
  unsaved: "Unsynced changes", refresh: "Refresh",
  sidebarCollapse: "Collapse navigation", sidebarExpand: "Expand navigation",
  aiMindMapTitle: "Create mind map with AI", aiMindMapHint: "Use pasted text, a clipboard screenshot, PDF, DOCX or PPTX. Review and edit the result before applying it to the canvas.", aiSourceFile: "File or image", chooseAiFile: "Choose or drop a file", aiFileHint: "PDF · DOCX · PPTX · TXT · Markdown · CSV · JPG · PNG · WebP · GIF · maximum 10 MB", pasteFromClipboard: "Paste from clipboard", clipboardSourceHint: "Text is pasted directly; a copied image is sent as a visual source.", clipboardEmpty: "The clipboard is empty.", clipboardReadError: "Clipboard access was blocked. Allow permission or paste the content into the text box.", aiFileRequired: "Choose a file first.", extractedPreview: "Review extracted text", generateSelectedPages: "Generate selected pages", generatingMindMap: "Reading the source and generating a mind map…",
} as const;
export type MessageKey = keyof typeof en;
export const vi: Record<MessageKey, string> = {
  title: "Tiêu đề", commandPalette: "Thao tác nhanh", commandSearch: "Tìm project và thao tác…", commandHint: "Mở bằng Ctrl/⌘ + K", noCommands: "Không có project hoặc thao tác phù hợp", goToFlashcards: "Mở flashcard", openSettings: "Mở cài đặt", importProject: "Nhập project",
  copyElements: "Sao chép phần tử", pasteElements: "Dán phần tử",
  selectedElements: "phần tử đã chọn", bringFront: "Đưa lên trên cùng", sendBack: "Đưa xuống dưới cùng", bringForward: "Lên một lớp", sendBackward: "Xuống một lớp",
  group: "Gộp nhóm", ungroup: "Tách nhóm", addChild: "Thêm nhánh con", addSibling: "Thêm nhánh cùng cấp", reparentHint: "Giữ Alt rồi kéo một node lên node khác để đổi cha. Shift+Enter sửa nhãn.",
  fitCanvas: "Vừa màn hình", fitSelection: "Đến phần đã chọn", minimap: "Bản đồ nhỏ", favorites: "Yêu thích", trash: "Thùng rác", restore: "Khôi phục", favorite: "Thêm yêu thích", unfavorite: "Bỏ yêu thích", moveToTrash: "Đưa vào thùng rác", projectActions: "Thao tác project", copySuffix: "bản sao", trashEmpty: "Thùng rác trống", trashHint: "Bạn có thể khôi phục các file tại đây. File chưa bị xóa vĩnh viễn.",
  arrangeMap: "Sắp xếp mind map",
  flashcards: "Flashcard", flashcardsHint: "Biến ghi chú thành các câu hỏi nhỏ để ôn tập.", decks: "Bộ thẻ", newDeck: "Bộ thẻ mới", renameDeck: "Đổi tên bộ thẻ", deleteDeck: "Xóa bộ thẻ", deleteDeckHint: "Xóa “{{name}}” và toàn bộ thẻ bên trong? Không thể hoàn tác.", deckName: "Tên bộ thẻ", noDecks: "Chưa có bộ thẻ", chooseDeck: "Chọn một bộ thẻ", chooseDeckHint: "Tạo bộ thẻ, sau đó thêm thẻ đầu tiên.", linkProject: "Liên kết project", noLinkedProject: "Không liên kết project", linkedProject: "Project liên kết", cardCount: "{{count}} thẻ", dueCount: "{{count}} thẻ đến hạn", newCard: "Thẻ mới", editCard: "Sửa thẻ", deleteCard: "Xóa thẻ", allCards: "Tất cả thẻ", review: "Ôn tập", startReview: "Bắt đầu ôn", noCards: "Bộ thẻ chưa có thẻ", noCardsHint: "Thêm câu hỏi và câu trả lời để bắt đầu ôn.", questionSide: "Câu hỏi", answerSide: "Câu trả lời", questionPlaceholder: "Bạn muốn ghi nhớ điều gì?", answerPlaceholder: "Viết câu trả lời hoặc lời giải thích…", sourcePage: "Trang nguồn", optional: "Không bắt buộc", flashcardNameRequired: "Hãy nhập tên bộ thẻ.", flashcardSidesRequired: "Hãy nhập cả câu hỏi và câu trả lời.", flashcardPageInvalid: "Trang nguồn phải là số nguyên dương.", flashcardCloudHint: "Flashcard được lưu trong Supabase theo tài khoản này.", flashcardLocalHint: "Flashcard đang lưu trên trình duyệt cho đến khi chạy migration cơ sở dữ liệu.", dueNow: "Đến hạn", nextReview: "Ôn lại {{date}}", showAnswer: "Hiện câu trả lời", ratePrompt: "Bạn nhớ thẻ này tốt đến mức nào?", again: "Quên", hard: "Khó", good: "Tốt", easy: "Dễ", reviewProgress: "{{current}} / {{total}}", reviewKeyboardHint: "Đánh giá được lưu ngay.", reviewComplete: "Đã ôn xong", reviewCompleteHint: "Bạn đã ôn {{count}} thẻ.", nothingDue: "Chưa có thẻ đến hạn", nothingDueHint: "Hiện không có thẻ nào đang chờ ôn.", backToCards: "Quay lại danh sách", newCards: "Thẻ mới", difficultCards: "Thẻ khó", learnedCards: "Đã học", reviewDue: "Ôn thẻ đến hạn", reviewNew: "Học thẻ mới", reviewDifficult: "Luyện thẻ khó", dailyGoal: "Mục tiêu mỗi ngày", sessionProgress: "Tiến độ phiên học", cardSearch: "Tìm thẻ…",
  generateFlashcards: "Tạo bằng AI", aiFlashcardHint: "Dùng văn bản dán vào, canvas project, ảnh từ clipboard hoặc file/hình ảnh được hỗ trợ. AI sẽ trả bản xem trước có thể chỉnh sửa; chỉ thêm khi bạn bấm áp dụng.", aiSource: "Nguồn", aiSourceText: "Dán văn bản", aiSourceProject: "Canvas project", aiSourcePdf: "Tài liệu PDF", sourceText: "Văn bản nguồn", sourceTextPlaceholder: "Dán ghi chú hoặc văn bản đã trích xuất muốn ôn tập…", sourceProject: "Project", chooseProject: "Chọn project", sourceProjectHint: "Phần chữ và nhãn mind-map trong project sẽ được gửi lên server.", maxGeneratedCards: "Số thẻ tối đa", aiMaxCardsInvalid: "Chọn từ 3 đến 50 thẻ.", generatingFlashcards: "Đang đọc nguồn và tạo flashcard…", aiPreviewHint: "Kiểm tra từng câu hỏi và câu trả lời. Bạn có thể sửa hoặc xóa trước khi thêm vào bộ thẻ.", flashcardSetTitle: "Tên bản xem trước", removePreviewCard: "Xóa thẻ xem trước", addPreviewCard: "Thêm thẻ xem trước", backToSource: "Quay lại nguồn", applyToDeck: "Thêm vào bộ thẻ", generatePreview: "Tạo bản xem trước", aiTextRequired: "Hãy dán văn bản nguồn trước.", aiProjectRequired: "Hãy chọn project trước.", aiProjectEmpty: "Project này không có chữ hoặc nhãn mind-map để đọc.", aiPdfRequired: "Hãy chọn PDF trước.", aiFlashcardError: "Không tạo được flashcard.",
  workspace: "Workspace", recent: "File gần đây", folders: "Thư mục", manageFolders: "Quản lý thư mục", newFolder: "Thư mục mới", folderActions: "Thao tác thư mục", renameFolder: "Đổi tên thư mục", deleteFolder: "Xóa thư mục", deleteFolderHint: "Các project trong thư mục sẽ được chuyển về Workspace. Chỉ thư mục bị xóa.", copy: "Sao chép", paste: "Dán", fileActions: "Thao tác file", emptyFolder: "Thư mục này đang trống", deleteFileHint: "Đưa project này vào thùng rác?", theme: "Giao diện", themeChoose: "Chọn bảng màu", themeLightCollection: "Theme sáng", themeDarkCollection: "Theme tối", themeLight: "Sáng Aurora", themeLightHint: "Nền trắng ngà với điểm nhấn tím rực rỡ.", themeOcean: "Gió biển Ocean", themeOceanHint: "Xanh băng thoáng nhẹ với điểm nhấn biển và cyan.", themeMint: "Sương bạc hà", themeMintHint: "Nền bạc hà tươi với sắc teal tương phản rõ.", themeSunset: "Hoàng hôn Coral", themeSunsetHint: "Kem ấm, san hô và cam quýt giàu năng lượng.", themeBerry: "Berry Pop", themeBerryHint: "Nền hồng dịu với sắc mâm xôi nổi bật.", themeDark: "Tối Midnight", themeDarkHint: "Nền mận đậm với sắc tím sáng tương phản.", themeCobalt: "Đêm Cobalt", themeCobaltHint: "Xanh navy sâu với điểm nhấn xanh điện.", themeCyber: "Cyber Teal", themeCyberHint: "Nền cyan tối với điểm nhấn aqua phát sáng.", themeForest: "Rừng Emerald", themeForestHint: "Nền xanh rừng đậm với điểm nhấn bạc hà.", themeSlate: "Đá Nordic", themeSlateHint: "Graphite lạnh với sắc xanh tím dịu, rõ nét.",
  mobileMenu: "Mở điều hướng", collapseFolder: "Thu thư mục", expandFolder: "Mở thư mục", resizeSidebar: "Đổi độ rộng thanh điều hướng", resetSidebarWidth: "Bấm đúp để đặt lại độ rộng", cloudConflictTitle: "Chọn phiên bản cần giữ", cloudConflictHint: "Project đã thay đổi trên cloud trong khi thiết bị này còn chỉnh sửa local. Autosave đang tạm dừng để không âm thầm ghi đè dữ liệu.", deviceVersion: "Bản trên thiết bị này", latestCloudVersion: "Bản cloud mới nhất", conflictSafety: "MindCanvas sẽ tạo một mốc khôi phục trước khi thay thế bất kỳ phiên bản nào.", useCloudVersion: "Dùng bản cloud", saveAsCopy: "Lưu bản thiết bị thành bản sao", saveDeviceToCloud: "Lưu bản thiết bị lên cloud",
  newProject: "Project mới", projects: "Project", untitled: "Canvas chưa đặt tên", name: "Tên",
  create: "Tạo", cancel: "Hủy", close: "Đóng", save: "Lưu", open: "Mở",
  rename: "Đổi tên", move: "Chuyển thư mục", noFolder: "Không có thư mục", search: "Tìm project…",
  newest: "Chỉnh sửa gần nhất", alphabetical: "Tên A–Z", empty: "Bắt đầu từ ý tưởng của bạn",
  emptyHint: "Tạo canvas trắng hoặc nhập file MindCanvas.", noResults: "Không có project phù hợp",
  local: "Trên thiết bị này", cloud: "Không gian đám mây", guest: "Khách", login: "Đăng nhập Google",
  logout: "Đăng xuất", checking: "Đang kiểm tra phiên…", loading: "Đang tải…", settings: "Cài đặt",
  language: "Ngôn ngữ", saved: "Đã lưu đám mây", localSaved: "Đã lưu trên máy",
  saving: "Đang lưu…", pending: "Chờ đồng bộ", offline: "Offline · giữ bản trên máy",
  syncCenter: "Trung tâm đồng bộ", syncCenterCloudHint: "Xem dữ liệu đang lưu trên thiết bị và các thay đổi đang chờ tải lên workspace đám mây riêng của bạn.", syncCenterLocalHint: "Workspace khách chỉ lưu trên thiết bị này. Hãy đăng nhập khi muốn đồng bộ giữa nhiều thiết bị.", networkOnline: "Đang có mạng", networkOffline: "Đang offline", networkOnlineHint: "Có thể kết nối dịch vụ đám mây.", networkOfflineHint: "Bạn vẫn có thể tiếp tục chỉnh sửa trên máy.", syncUpToDate: "Cloud đã đồng bộ", syncCloud: "Đồng bộ đám mây", syncDeviceOnly: "Bộ nhớ thiết bị", pendingFiles: "{{count}} file đang chờ", signInToSync: "Đăng nhập để bật đồng bộ cloud.", syncQueue: "Đang chờ đồng bộ", syncQueueEmpty: "Không có thay đổi nào đang chờ đồng bộ.", syncLocalReady: "Project của bạn đã sẵn sàng trên thiết bị này.", offlineSafety: "Thay đổi được ghi vào kho offline trên thiết bị trước khi thử tải lên cloud.", syncNow: "Đồng bộ ngay",
  installApp: "Cài ứng dụng", installAppTitle: "Cài MindCanvas", installAppHint: "Cài web app để mở toàn màn hình, khởi động nhanh và truy cập offline các project đã mở trên thiết bị này.", installNow: "Cài trên thiết bị", appInstalled: "Đã cài ứng dụng", appInstalledHint: "MindCanvas đang chạy dưới dạng ứng dụng đã cài trên thiết bị này.", iosInstallHint: "Trên iPhone hoặc iPad, hãy mở trang này bằng Safari, bấm Chia sẻ rồi chọn Thêm vào Màn hình chính.", browserInstallHint: "Nếu nút cài chưa xuất hiện, hãy chọn Cài ứng dụng trong menu của trình duyệt.", pwaOfflineHint: "Giao diện editor và project đã lưu cache có thể mở khi mất mạng. AI, đăng nhập Google và đồng bộ cloud sẽ tiếp tục khi có mạng lại.", updateReady: "Đã có phiên bản MindCanvas mới.", updateNow: "Cập nhật ngay",
  saveError: "Lưu thất bại", retry: "Thử lại", error: "Đã xảy ra lỗi", import: "Nhập file",
  export: "Tải file về máy", exportSvg: "Xuất SVG", exportPng: "Xuất PNG", exportSvgHint: "Tải canvas dưới dạng ảnh vector có thể phóng to.", exportPngHint: "Tải canvas dưới dạng ảnh PNG.", importError: "File MindCanvas không hợp lệ (tối đa 40 MB).",
  exportHint: "Tải bản sao riêng tư. Gửi file để chia sẻ; không cấp quyền truy cập đám mây.",
  select: "Chọn", hand: "Di chuyển canvas", text: "Chữ", pen: "Bút", highlighter: "Bút đánh dấu",
  insertMedia: "Chèn đa phương tiện", insertMediaHint: "Thêm hình ảnh, video hoặc tệp âm thanh", recordAudio: "Ghi âm", stopRecording: "Dừng ghi âm", recording: "Đang ghi {{seconds}} giây", media: "Đa phương tiện", image: "Hình ảnh", video: "Video", audio: "Âm thanh", mediaFileTooLarge: "Tệp đa phương tiện quá lớn (tối đa 12 MB).", recordingUnsupported: "Trình duyệt này không hỗ trợ ghi âm.", recordingPermissionDenied: "Bạn đã từ chối quyền dùng micro.",
  embedWeb: "Nhúng trang web", embedUrl: "URL web hoặc video", embedTitle: "Tiêu đề", embedPlaceholder: "https://… hoặc liên kết YouTube", embedHint: "Liên kết YouTube sẽ thành trình phát trực tiếp. Một số website chặn việc hiển thị trong trang khác.", insertEmbed: "Chèn nội dung nhúng", embed: "Nội dung nhúng", webPage: "Trang web", youtube: "YouTube", embedBlocked: "Website này có thể chặn xem qua iframe.", pasteImage: "Dán ảnh chụp màn hình", pasteImageHint: "Đọc hình ảnh từ clipboard hệ thống",
  rect: "Chữ nhật", ellipse: "Elip", connector: "Đường nối", node: "Node sơ đồ tư duy",
  newNode: "Ý mới", rootNode: "Ý chính", newText: "Nhập nội dung", editText: "Sửa nội dung",
  undo: "Hoàn tác", redo: "Làm lại", duplicate: "Nhân đôi", delete: "Xóa", versionHistory: "Lịch sử phiên bản", versionHint: "Tạo mốc lưu rõ ràng khi bạn muốn có điểm khôi phục ổn định. Di chuyển và phóng to canvas không tạo thêm bước lịch sử.", saveCheckpoint: "Lưu mốc phiên bản", noVersions: "Chưa có mốc phiên bản", cloudVersion: "Đám mây", localVersion: "Thiết bị này", restoreCreatesUndo: "Khôi phục tạo một thay đổi có thể hoàn tác và trạng thái hiện tại sẽ được lưu mốc trước.", zoomIn: "Phóng to",
  zoomOut: "Thu nhỏ", resetZoom: "Đặt lại góc nhìn", properties: "Thuộc tính", layers: "Phần tử", searchElements: "Tìm phần tử…", noElements: "Canvas chưa có phần tử", noElementsFound: "Không có phần tử phù hợp", grouped: "Đã gộp nhóm", layerDragHint: "Kéo một hàng để đổi thứ tự. Hàng đầu tiên nằm trên cùng.", snap: "Đường căn thông minh", alignLeft: "Căn trái", alignCenter: "Căn giữa", alignRight: "Căn phải", alignTop: "Căn trên", alignMiddle: "Căn giữa dọc", alignBottom: "Căn dưới", distributeHorizontal: "Chia đều ngang", distributeVertical: "Chia đều dọc", rotate: "Xoay", lock: "Khóa", unlock: "Mở khóa", hide: "Ẩn", show: "Hiện",
  color: "Màu", label: "Nhãn", width: "Rộng", height: "Cao", rotation: "Góc xoay (độ)", resetRotation: "Đặt về 0°", crop: "Cắt khung", resetCrop: "Đặt lại crop", cropTop: "Trên %", cropRight: "Phải %", cropBottom: "Dưới %", cropLeft: "Trái %", trimStart: "Bắt đầu (giây)", trimEnd: "Kết thúc (giây)", trimHint: "Chỉ giới hạn khoảng phát; file gốc không bị thay đổi.", resetTrim: "Đặt lại đoạn cắt", clipboardImageUnavailable: "Không tìm thấy hình ảnh trong clipboard.", seconds: "giây", fontSize: "Cỡ chữ", opacity: "Độ đậm", alpha: "Độ trong suốt", resetAlpha: "Đặt lại độ trong suốt", bold: "In đậm", italic: "In nghiêng", underline: "Gạch chân", bulletedList: "Danh sách dấu chấm", checklist: "Danh sách kiểm tra", textBackground: "Nền chữ", clearBackground: "Bỏ nền chữ",
  canvasBackground: "Nền canvas", backgroundDots: "Chấm", backgroundGrid: "Ô lưới", backgroundRuled: "Giấy kẻ ngang", backgroundGraph: "Giấy đồ thị", backgroundIsometric: "Lưới phối cảnh", backgroundPlain: "Trắng",
  stroke: "Độ dày nét", collapse: "Thu nhánh", expand: "Mở nhánh",
  canvasHint: "Kéo vùng trống để chọn · Shift+bấm để chọn thêm · Space+kéo để di chuyển canvas",
  connectorHint: "Chọn node hoặc hình nguồn, sau đó chọn đích.",
  selectHint: "Chọn phần tử để thay đổi vị trí, kích thước hoặc màu.",
  textHint: "Bấm vị trí để nhập chữ. Escape hủy; Ctrl/⌘ + Enter hoàn tất.",
  ai: "PDF → sơ đồ tư duy", choosePdf: "Chọn PDF", pdfHint: "Tối đa 10 MB. Cần PDF có văn bản.", pdfPreview: "Xem trước PDF", pageRange: "Trang", allPages: "Tất cả trang", fromPage: "Từ trang", toPage: "Đến trang", applyTo: "Thêm vào", currentCanvas: "Canvas hiện tại", newCanvas: "Canvas mới", selectedPages: "Trang đã chọn", previewChanges: "Kiểm tra thay đổi do AI tạo trước khi áp dụng.", rollbackHint: "Thao tác áp dụng tạo một bước có thể hoàn tác.", noTextPages: "Không tìm thấy văn bản đọc được trong các trang đã chọn.",
  generate: "Tạo bản xem trước", generating: "Đang đọc PDF và tạo sơ đồ…", apply: "Thêm vào canvas",
  aiHint: "Kiểm tra và sửa nhãn bên dưới. Nội dung canvas hiện tại được giữ nguyên.",
  aiError: "Không xử lý được PDF. Kiểm tra kết nối API và cấu hình model.", aiQueueBusy: "AI đang phục vụ yêu cầu khác. Hãy đợi khoảng 15 giây rồi thử lại.", aiTemporarilyBusy: "Gemini đang bận hoặc tạm giới hạn quota dùng chung. MindCanvas đã tự thử lại và chuyển model dự phòng; hãy đợi khoảng 30 giây rồi thử lại.", aiModelUnavailable: "Không model Gemini nào trong cấu hình khả dụng với key của server. Chủ dự án cần kiểm tra GEMINI_MODELS trên service API.", aiSessionExpired: "Phiên đăng nhập đã hết hạn. Hãy đăng xuất, đăng nhập Google lại rồi thử tiếp.",
  aiDemo: "Server trả dữ liệu demo. Hãy cấu hình AI thật trước khi thêm vào canvas.",
  aiSelectionTitle: "AI cho vùng đã chọn", aiSelectionHint: "Chỉ xử lý chữ hoặc node sơ đồ tư duy đang chọn. Bạn được xem và sửa kết quả trước khi áp dụng.", aiSelectionAction: "Tác vụ AI", aiSummarize: "Tóm tắt", aiExplain: "Giải thích", aiRewrite: "Viết lại", aiExpand: "Mở rộng nhánh", aiSelectedContent: "Nội dung đã chọn", aiSelectionWorking: "Gemini đang xử lý vùng đã chọn…", aiSelectionError: "Không xử lý được vùng đã chọn.", aiResult: "Kết quả có thể sửa", aiChildIdeas: "Các ý con", aiChildIdea: "Ý con", askAiSelection: "Dùng AI cho vùng chọn", selectTextForAi: "Hãy chọn chữ hoặc node sơ đồ tư duy để dùng AI.",
  loginRequired: "Đăng nhập để lưu PDF và dùng AI.", nodes: "node", edges: "đường nối",
  page: "Trang", openSource: "Mở PDF nguồn", openNewTab: "Mở tab mới", sourceError: "Không mở được PDF nguồn.", help: "Phím tắt", helpText: "V chọn · H di chuyển canvas · T chữ · P bút · R chữ nhật · O elip · C nối · Ctrl/⌘+K thao tác nhanh · Ctrl/⌘+Z hoàn tác · Ctrl/⌘+D nhân đôi · Ctrl/⌘+S lưu",
  accountHint: "Project đám mây thuộc tài khoản đã đăng nhập. Project local chỉ ở trình duyệt này.",
  fileTooLarge: "File vượt quá 10 MB.", noFolders: "Chưa có thư mục", copied: "Đã tải bản sao",
  updated: "Cập nhật", saveBeforeLeave: "Giữ tab mở đến khi lưu xong, hoặc tải bản sao dự phòng.",
  drawHint: "Kéo để vẽ. Đổi sang Chọn để di chuyển từng nét vẽ.",
  unsaved: "Thay đổi chưa đồng bộ", refresh: "Tải lại",
  sidebarCollapse: "Thu gọn thanh điều hướng", sidebarExpand: "Mở rộng thanh điều hướng",
  aiMindMapTitle: "Tạo mind map bằng AI", aiMindMapHint: "Dùng văn bản, ảnh chụp từ clipboard, PDF, DOCX hoặc PPTX. Kiểm tra và sửa kết quả trước khi thêm vào canvas.", aiSourceFile: "File hoặc hình ảnh", chooseAiFile: "Chọn hoặc thả file vào đây", aiFileHint: "PDF · DOCX · PPTX · TXT · Markdown · CSV · JPG · PNG · WebP · GIF · tối đa 10 MB", pasteFromClipboard: "Dán từ clipboard", clipboardSourceHint: "Văn bản được dán trực tiếp; ảnh đã copy sẽ được gửi như nguồn hình ảnh.", clipboardEmpty: "Clipboard đang trống.", clipboardReadError: "Trình duyệt đã chặn clipboard. Hãy cấp quyền hoặc dán nội dung vào ô văn bản.", aiFileRequired: "Hãy chọn file trước.", extractedPreview: "Xem văn bản đã trích xuất", generateSelectedPages: "Tạo từ các trang đã chọn", generatingMindMap: "Đang đọc nguồn và tạo mind map…",
};
type Language = "vi" | "en";
type ThemeContextValue = {
  /** Effective theme used to render the app. It can be a temporary preview. */
  theme: Theme;
  /** Persisted user choice; this remains stable while hovering a preview card. */
  selectedTheme: Theme;
  previewTheme: Theme | null;
  setTheme: (theme: Theme) => void;
  preview: (theme: Theme) => void;
  clearPreview: () => void;
};
const ThemeContext = createContext<ThemeContextValue>({ theme: "light", selectedTheme: "light", previewTheme: null, setTheme: () => {}, preview: () => {}, clearPreview: () => {} });
type TranslationValues = Record<string, string | number>;
const Context = createContext({ language: "vi" as Language, setLanguage: (_: Language) => {}, t: (key: MessageKey, values?: TranslationValues): string => {
  let message = vi[key];
  for (const [name, value] of Object.entries(values ?? {})) message = message.replaceAll(`{{${name}}}`, String(value));
  return message;
} });
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => { try { return localStorage.getItem("mindcanvas:language") === "en" ? "en" : "vi"; } catch { return "vi"; } });
  const [selectedTheme, setSelectedTheme] = useState<Theme>(() => { try { const saved = localStorage.getItem("mindcanvas:theme"); return isTheme(saved) ? saved : DEFAULT_THEME; } catch { return DEFAULT_THEME; } });
  const [previewTheme, setPreviewTheme] = useState<Theme | null>(null);
  const theme = previewTheme ?? selectedTheme;
  const setTheme = useCallback((next: Theme) => { setSelectedTheme(next); setPreviewTheme(null); }, []);
  const preview = useCallback((next: Theme) => setPreviewTheme(next), []);
  const clearPreview = useCallback(() => setPreviewTheme(null), []);
  useEffect(() => { document.documentElement.lang = language; try { localStorage.setItem("mindcanvas:language", language); } catch {} }, [language]);
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')?.setAttribute("content", themeBrowserColor(theme));
  }, [theme]);
  useEffect(() => { try { localStorage.setItem("mindcanvas:theme", selectedTheme); } catch {} }, [selectedTheme]);
  return <Context.Provider value={{ language, setLanguage, t: (key, values) => {
    let message = (language === "vi" ? vi : en)[key];
    for (const [name, value] of Object.entries(values ?? {})) message = message.replaceAll(`{{${name}}}`, String(value));
    return message;
  } }}><ThemeContext.Provider value={{ theme, selectedTheme, previewTheme, setTheme, preview, clearPreview }}>{children}</ThemeContext.Provider></Context.Provider>;
}
export const useLanguage = () => useContext(Context);
export const useTheme = () => useContext(ThemeContext);
