export const LAB_MODES = ["animation", "simulation", "explainer", "experiment", "algorithm", "data", "scenario", "freeform"] as const;
export type LabMode = typeof LAB_MODES[number];
export type LabPresentation = "auto" | "scene" | "document";
export type LabViewerConfig = { presentation: LabPresentation; aspectRatio: "16:9" | "4:3" | "1:1" };
export const DEFAULT_LAB_VIEWER: LabViewerConfig = { presentation: "auto", aspectRatio: "16:9" };
export const MAX_LAB_THUMBNAIL = 200_000;

const modes: Record<LabMode, { vi: string; en: string; hintVi: string; hintEn: string; example: string; instructions: string }> = {
  animation: { vi: "Hoạt họa tương tác", en: "Interactive animation", hintVi: "Các thành phần chuyển động và tác động lên nhau.", hintEn: "Objects move and affect one another.", example: "Điện phân: thể hiện ion, điện cực, phản ứng và sản phẩm; cho phép tạm dừng và xem từng bước.", instructions: "Model the actors, states and causal interactions, not decorative motion alone. Synchronize labels and reactions with state. Include play, pause, step, animation speed and reset. Distinguish animation speed from real process rate. For electrolysis, require the electrolyte, electrode material and conditions; explain ion migration, oxidation/reduction and products consistently with those conditions. Do not assume every ion is discharged or invent a quantitative reaction model." },
  simulation: { vi: "Mô phỏng định lượng", en: "Quantitative simulation", hintVi: "Đổi thông số, quan sát kết quả và biểu đồ.", hintEn: "Adjust parameters and inspect results and graphs.", example: "Đổi góc bắn và vận tốc; so sánh quỹ đạo, tầm xa và độ cao.", instructions: "Define the mathematical model, equations, units, valid parameter ranges and numerical limits. Controls must change actual computed outputs. Include boundary tests and expected numeric values with tolerances. Label approximations and unsupported estimates." },
  explainer: { vi: "Trực quan kiến thức", en: "Visual explanation", hintVi: "Khám phá kiến thức qua từng lớp và mối liên hệ.", hintEn: "Explore concepts in layers and relationships.", example: "Giải thích liên kết ion qua từng bước, chọn nguyên tử để xem electron và điện tích.", instructions: "Break complex knowledge into progressive layers and a clear explanatory sequence. Let the learner select parts to inspect explanations. Connect representations to concepts and misconceptions. Never add meaningless sliders or invented equations. Provide previous/next steps and a summary." },
  experiment: { vi: "Thí nghiệm ảo", en: "Virtual experiment", hintVi: "Thao tác, ghi nhận, so sánh và kết luận.", hintEn: "Manipulate, observe, compare and conclude.", example: "Khảo sát ảnh hưởng của một biến: đặt giả thuyết, giữ các biến khác cố định, ghi bảng quan sát.", instructions: "Organize hypothesis, equipment, independent/dependent/controlled variables, procedure, observations and conclusion. Allow repeated trials and comparison. Label generated data as simulated, not real measurements. Explain assumptions and safe conceptual limits." },
  algorithm: { vi: "Thuật toán từng bước", en: "Step-by-step algorithm", hintVi: "Theo dõi dữ liệu, từng bước và mã tương ứng.", hintEn: "Trace data, steps and corresponding code.", example: "HeapSort: nhập mảng, xem xây heap, từng lần đổi chỗ và kết quả sắp xếp.", instructions: "Implement the actual algorithm with deterministic trace states, highlighted pseudocode, invariants and final output. Provide editable input, play/pause/step/reset. Test duplicates, empty/single-element inputs and sorted/reverse inputs. Do not show an animation unrelated to computed steps." },
  data: { vi: "Phân tích dữ liệu", en: "Data exploration", hintVi: "Đọc bảng, khám phá biểu đồ và so sánh.", hintEn: "Explore tables, charts and comparisons.", example: "So sánh nhiệt độ theo tháng bằng bảng và biểu đồ; nhận xét xu hướng và ngoại lệ.", instructions: "Include a source-labelled dataset, table, accessible chart, filters and comparison questions. Validate missing and invalid numeric values. Label synthetic data clearly. Do not imply causation from correlation. Use embedded data or local text/file input; never fetch data." },
  scenario: { vi: "Tình huống tương tác", en: "Interactive scenario", hintVi: "Lựa chọn hành động, xem hệ quả và phản hồi.", hintEn: "Choose actions and inspect consequences and feedback.", example: "Tâm lý người tiêu dùng đồ gia dụng: so sánh giá, độ bền và bảo hành qua các tình huống lựa chọn.", instructions: "Define the scenario, choices, branching states and justified feedback. Support restarting and comparing decisions. Do not invent psychological probabilities or numeric scores without an explicit model. Present outcomes as educational cases, not universal predictions. Do not require physics equations or pause controls unless useful." },
  freeform: { vi: "Tự do", en: "Custom Lab", hintVi: "Mô tả trải nghiệm riêng hoặc dùng HTML có sẵn.", hintEn: "Describe your own experience or import HTML.", example: "Tạo một trò chơi học tập có hướng dẫn, phản hồi và nút chơi lại.", instructions: "Follow the requested learning experience. Choose controls appropriate to the task. Do not force scientific equations, numeric simulation or scoring when irrelevant." },
};
export function isLabMode(value: unknown): value is LabMode { return typeof value === "string" && LAB_MODES.includes(value as LabMode); }
export function labModeInfo(mode: LabMode, language: string) {
  const item = modes[mode];
  return { label: language === "vi" ? item.vi : item.en, hint: language === "vi" ? item.hintVi : item.hintEn, example: item.example, instructions: item.instructions };
}
export function cleanLabViewer(value: unknown): LabViewerConfig {
  const item = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return { presentation: item.presentation === "scene" || item.presentation === "document" ? item.presentation : "auto", aspectRatio: item.aspectRatio === "4:3" || item.aspectRatio === "1:1" ? item.aspectRatio : "16:9" };
}
export function cleanLabThumbnail(value: unknown): string | undefined {
  return typeof value === "string" && value.length <= MAX_LAB_THUMBNAIL && /^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(value) ? value : undefined;
}
